package translator

// F1Glossary maps common F1 radio terms to Chinese translations.
// Injected into the DeepSeek system prompt for accurate translation.
var F1Glossary = map[string]string{
	"Box":                "进站 (Pit Stop)",
	"Box box box":        "进站进站进站（紧急进站指令）",
	"In in in":           "进来进来进来（进站指令）",
	"Stay out":           "留在赛道上",
	"Undercut":           "提前进站策略",
	"Overcut":            "延后进站策略",
	"DRS":                "减阻系统 (Drag Reduction System)",
	"Delta":              "时间差值",
	"Deg":                "轮胎衰退 (Degradation)",
	"Graining":           "轮胎起泡（表面撕裂）",
	"Blistering":         "轮胎起疱",
	"Flat spot":          "轮胎平点（锁死磨损）",
	"Push push push":     "全力进攻",
	"Hammer time":        "全力冲刺",
	"Lift and coast":     "升挡滑行（节省引擎/轮胎）",
	"Copy":               "收到/明白",
	"Understood":         "明白",
	"Affirm":             "确认",
	"Negative":           "否定/不行",
	"PU":                 "动力单元 (Power Unit)",
	"MGU-K":              "动能回收电机",
	"MGU-H":              "热能回收电机",
	"ERS":                "能量回收系统",
	"Deploy":             "释放电能",
	"Harvest":            "回收电能",
	"VSC":                "虚拟安全车 (Virtual Safety Car)",
	"SC":                 "安全车 (Safety Car)",
	"Formation lap":      "编队圈/暖胎圈",
	"In-lap":             "进站圈",
	"Out-lap":            "出站圈",
	"Flying lap":         "飞驰圈（计时圈）",
	"Purple sector":      "最快赛段（紫色）",
	"Green sector":       "个人最快赛段（绿色）",
	"Yellow sector":      "慢于个人最快（黄色）",
	"Track limits":       "赛道界限",
	"Blue flag":          "蓝旗（让车警告）",
	"Yellow flag":        "黄旗（危险警告）",
	"Red flag":           "红旗（比赛中断）",
	"Chequered flag":     "方格旗（比赛结束）",
	"Pit window":         "进站窗口",
	"Pit wall":           "P房/车队指挥墙",
	"Pit lane":           "维修区通道",
	"Dirty air":          "乱流/脏空气",
	"Clean air":          "干净空气",
	"Tow":                "尾流（利用前车减少风阻）",
	"Slipstream":         "尾流效应",
	"Lock-up":            "锁死（刹车过重）",
	"Understeer":         "转向不足/推头",
	"Oversteer":          "转向过度/甩尾",
	"Front wing":         "前翼",
	"Rear wing":          "尾翼",
	"Downforce":          "下压力",
	"Drag":               "阻力",
	"Stint":              "连续驾驶段（一套轮胎的使用周期）",
	"Compound":           "轮胎配方",
	"Soft":               "软胎",
	"Medium":             "中性胎",
	"Hard":               "硬胎",
	"Intermediate":       "中间胎（浅雨胎）",
	"Wet":                "全雨胎",
	"Target":             "目标圈速",
	"Gap":                "间距/差距",
	"Interval":           "车距",
	"Switchback":         "反切（出弯超越）",
	"Defend":             "防守",
	"Attack":             "进攻",
	"Battery":            "电池",
	"Mode":               "引擎模式",
	"Strat mode":         "策略模式",
	"Multi":              "多功能旋钮设置",
	"Critical":           "关键/危急",
	"Damage":             "损伤/受损",
	"Penalty":            "处罚",
	"Five-second penalty": "5秒加罚",
	"Ten-second penalty":  "10秒加罚",
	"Stop-go penalty":    "进站加罚",
	"Black and white flag": "黑白旗（警告）",
	"Drink":              "喝水（启动饮水系统）",
	"Head down":          "专注驾驶/低头干活",
	"Keep your head down": "保持专注",
	"Swap position":      "交换位置/让位",
	"Team order":         "车队指令",
}

// BuildGlossaryPrompt formats the glossary for injection into the system prompt.
func BuildGlossaryPrompt() string {
	result := "## F1 术语参考表\n"
	for en, zh := range F1Glossary {
		result += "- " + en + " → " + zh + "\n"
	}
	return result
}
